name: Utku Yurter
bio: 'Artificial Intelligence - Cyber Security'
picture: 'assets/images/profile.jpg'

url: http://utkuyurter.github.io/
# your url: http://USERNAME.github.io/
permalink: /:MyBlog/

#analytics: 'UA-MYANALYTICS'
#disqus: mydisqus
facebook: https://www.facebook.com/utku.yurter
#twitter: mytwitter
#instagram: myinstagram
linkedin: https://www.linkedin.com/in/utku-yurter-b877a3105?trk=nav_responsive_tab_profile_pic
#youtube: myyoutube
#spotify: myspotify
github: https://github.com/utkuyurter
email: utkuyurter@gmail.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor]

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com
